In [4]:
import numpy as np

# Исходная матрица квадратичной формы
A = np.array([
    [-1, 2, 2, -1],
    [2, -4, -4, 2],
    [2, -4, -4, 2],
    [-1, 2, 2, -1]
])

# Матрица преобразования
B = np.array([
    [-38, 95, -159, -472],
    [39, -97, 163, 483],
    [36, -90, 151, 448],
    [15, -38, 64, 190]
])

# Находим мат рицу квадратичной формы в новом базисе
tilde_A = B.T @ A @ B

# Выводим результат
print("Матрица квадратичной формы в новом базисе:")
print(tilde_A)

Матрица квадратичной формы в новом базисе:
[[  -29929    74563  -125079  -370912]
 [   74563  -185761   311613   924064]
 [ -125079   311613  -522729 -1550112]
 [ -370912   924064 -1550112 -4596736]]
